import { fakerCS_CZ } from "@faker-js/faker";
import {UserData} from "../ts-types/types";
/*
Function createAutoCzUser fill registration data with fake data generated by Faker library.
 */
export function createAutoCzUser(): UserData {
    return {
        firstName: fakerCS_CZ.person.firstName('male'),
        lastName: fakerCS_CZ.person.lastName('male'),
        dateOfBirth: fakerCS_CZ.date.birthdate({ mode: 'age', min: 21, max: 40 }).toISOString().split('T')[0],
        country: 'CZ',
        houseNumber: fakerCS_CZ.location.buildingNumber(),
        street: fakerCS_CZ.location.street(),
        city: fakerCS_CZ.location.city(),
        state: fakerCS_CZ.location.state(),
        postalCode: fakerCS_CZ.location.zipCode(),
        phone: `7${fakerCS_CZ.number.int({ min: 20, max: 99 })}${fakerCS_CZ.number.int({ min: 100, max: 999 })}${fakerCS_CZ.number.int({ min: 100, max: 999 })}`,
        emailAddress: fakerCS_CZ.internet.email(),
        password: `Qa1!${fakerCS_CZ.internet.password({ length: 10 })}`,
    };
}

export const manualTestUser: UserData = {
firstName: 'Oleh',
    lastName: 'Mykhayliv',
    dateOfBirth: '1994-03-31',
    country:  'CZ',
    postalCode: '130 00',
    houseNumber: '1847/31',
    street: 'Jana Zelivskeho',
    city: 'Prague',
    state: 'Czechia',
    phone: '721720305',
    emailAddress: 'mykhayliv88777@gmail.com',
    password: 'Europe2026$'
}
